# Generated by Django 5.2.4 on 2025-09-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('discription', models.TextField(verbose_name='상품설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('is_published', models.BooleanField(verbose_name='')),
            ],
        ),
    ]
